#VERSION: 0.0.1
#
#install postgresql 
---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
  - name: update apt
    apt: update_cache=yes
  - name: install postgresql
    action: apt pkg={{item}} state=installed
    with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: test 
    dbuser: test 
    dbpassword: test  

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
