#VERSION: 0.0.1
#
#install postgresql 
---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
  - name: update apt
    apt: update_cache=yes
  - name: install postgresql
    action: apt pkg={{item}} state=installed
    with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2

  - name: Ensure PostgreSQL is listening on all localhost
    lineinfile: dest=/etc/postgresql/9.1/main/postgresql.conf
      regexp='^#?listen_addresses\s*='
      line="listen_addresses = '*'"
      state=present
    notify: restart postgresql

  - lineinfile: dest=/etc/postgresql/9.1/main/pg_hba.conf
                 regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
                 line='host all all 0.0.0.0/0 md5'
                 insertbefore=BOF
    notify: restart postgresql

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: test 
    dbuser: test 
    dbpassword: test  

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
